# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.IntegerField()),
                ('nome_cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dep', models.IntegerField()),
                ('nome_dep', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matr_func', models.IntegerField()),
                ('reg_func', models.CharField(max_length=14)),
                ('nome_func', models.CharField(max_length=80)),
                ('endereco_func', models.CharField(max_length=200)),
                ('email_func', models.CharField(max_length=80)),
                ('datanasc_func', models.DateField()),
                ('salario_func', models.FloatField()),
                ('pfpj_func', models.BooleanField()),
                ('cargo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuber.Cargo')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuber.Departamento')),
            ],
        ),
    ]
