# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_cli', models.CharField(max_length=14)),
                ('nome_cli', models.CharField(max_length=80)),
                ('email_cli', models.CharField(max_length=80)),
                ('apelido_cli', models.CharField(max_length=20)),
                ('endereco_cli', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custo', models.IntegerField()),
                ('nome_custo', models.CharField(max_length=30)),
                ('valor_custo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_fornec', models.CharField(max_length=14)),
                ('nome_fornec', models.CharField(max_length=50)),
                ('email_fornec', models.CharField(max_length=80)),
                ('endereco_fornec', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proj', models.IntegerField()),
                ('nome_proj', models.CharField(max_length=30)),
                ('valor_proj', models.FloatField()),
                ('estado_proj', models.CharField(max_length=14)),
            ],
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='cargo_id',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='datanasc_func',
            new_name='data_de_nascimento',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='dep_id',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='email_func',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='endereco_func',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='matr_func',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_func',
            new_name='nome_completo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='reg_func',
            new_name='num_registro',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='pfpj_func',
            new_name='pfpj',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='salario_func',
            new_name='salario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='funcionario',
            field=models.ManyToManyField(to='superuber.Funcionario'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='projeto',
            field=models.ManyToManyField(to='superuber.Projeto'),
        ),
        migrations.AddField(
            model_name='custo',
            name='fornecedor',
            field=models.ManyToManyField(to='superuber.Fornecedor'),
        ),
        migrations.AddField(
            model_name='custo',
            name='funcionario',
            field=models.ManyToManyField(to='superuber.Funcionario'),
        ),
        migrations.AddField(
            model_name='custo',
            name='projeto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuber.Projeto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='projeto',
            field=models.ManyToManyField(to='superuber.Projeto'),
        ),
    ]
