# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0002_auto_20180717_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='nome_cargo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='apelido_cli',
            new_name='apelido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email_cli',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco_cli',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_cli',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='custo',
            old_name='nome_custo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='custo',
            old_name='projeto_id',
            new_name='projeto',
        ),
        migrations.RenameField(
            model_name='custo',
            old_name='valor_custo',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='nome_dep',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='email_fornec',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='endereco_fornec',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome_fornec',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='estado_proj',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='nome_proj',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='valor_proj',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='id_cargo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='reg_cli',
        ),
        migrations.RemoveField(
            model_name='custo',
            name='id_custo',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='id_dep',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='reg_fornec',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='id_proj',
        ),
        migrations.AddField(
            model_name='cliente',
            name='num_registro',
            field=models.CharField(default=0, max_length=14, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='num_registro',
            field=models.CharField(default=0, max_length=14, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='custo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
