# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0005_auto_20180717_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='pfpj',
            new_name='pessoa_fisica',
        ),
    ]
