# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0006_auto_20180717_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='pessoa_fisica',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('PF', 'Pessoa F\xedsica'), ('PJ', 'Pessoa Jur\xeddica')], default='PF', max_length=2),
        ),
    ]
