# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0007_auto_20180717_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='estado',
            field=models.CharField(choices=[('CRD', 'Criado'), ('AND', 'Em andamento'), ('CLD', 'Conclu\xeddo'), ('CAN', 'Cancelado')], default='CRD', max_length=3),
        ),
    ]
