# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0008_auto_20180717_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='projeto',
            field=models.ManyToManyField(blank=True, null=True, to='superuber.Projeto'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuber.Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuber.Departamento'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='funcionario',
            field=models.ManyToManyField(blank=True, null=True, to='superuber.Funcionario'),
        ),
    ]
