# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0010_auto_20180717_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apelido',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
