# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0011_auto_20180717_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='valor',
            field=models.FloatField(blank=True),
        ),
    ]
