# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuber', '0012_auto_20180717_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_de_nascimento',
            field=models.DateField(verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_completo',
            field=models.CharField(max_length=80, verbose_name='nome completo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='num_registro',
            field=models.CharField(max_length=14, verbose_name='CPF/CNPJ'),
        ),
    ]
